language: node_js
node_js: stable

install:
  - npm install hexo

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "shw2018"
  - git config user.email "hwsun@std.uestc.edu.cn"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/shw2018/shw2018.github.io.git